[build]
  command = "cd JIYADFAMILY && npm install && npm run build"
  publish = "JIYADFAMILY/dist"


[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
