[build]
  command = "npm install && npm run build"
  publish = "my-vite-app/dist"

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
