[build]
  publish = "build"
  command = "npm install && run build"

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
