[build]
  command = "npm install && npm run build"
  publish = "my-vite-app/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
